### ISSUE TITLE
Support multi-party direct messages as a target type

### ISSUE THREAD

**Issue by justjake** [traveloka/slack-robot#35]
Slack now has multi-party direct messages, which behave like a new private group but have a lighter-weight user experience. It would be great if I could create new MPDMs and use MPDMs as a target in `res.text`; here's my proposed API:

```js
robot.listen(/introduce/, (req, res) => {
  res.text('hello, hello, i am the fine wonderful robot',
    '#general',
    'a_known_group',
    // could also do import mpdp from 'slack-robot/lib/mpdm'
    res.mpdm('@jake', '@rachel', '@matt')
  );
});
```

Adding MPDM support should be straight-forward, since MPDMs are emulated as groups; there's little need to modify functions other than [Response#_getTargets](https://github.com/traveloka/slack-robot/blob/master/src/Response.js#L447-L451) here to add a new MPDM target sentinel, and adding a new branch to [Response#_send](https://github.com/traveloka/slack-robot/blob/master/src/Response.js#L256) to handle opening the MPDM.

### API Info
mpim.open: https://api.slack.com/methods/mpim.open
mpim data type: https://api.slack.com/types/mpim

**Comment by pveyes** [comment]
Hi @justjake thanks for the feedback

As mpdm is just multiple people group together how about using a array (instead of a function wrapper like `res.mpdm`). So the code will be like this:

```js
robot.listen(/introduce/, (req, res) => {
  res.text('hello, hello, i am the fine wonderful robot',
    '#general',
    'a_known_group',
    // this will be treated as mpdm
    ['@jake', '@rachel', '@matt']
  );
});
```

This is probably a breaking change by looking at the code, but using array to send to multiple user is not commonly used anyway and we're not using it either in our company. Also, it make a lot more sense to group these people together as mpdm.

What do you think?

PS: I just realized that using multiple arguments is currently not supported

**Comment by justjake** [comment]
:clap: amazing!! I like the new API; varargs makes sense. Is it ok to have the user IDs in any order? Should they be sorted? That could make caching easier.
